### ISSUE TITLE
VirtualKeyboard - display non-printable characters

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#112]
Unicode chars, which have no graphic representation in the system's default font, are not displayed and not available.

Possible solutions:
- [ ] install and ship specific font to be used in virtual keyboard
- [ ] provide possibility to choose same font in transcription window
- [ ] add pseudo icon for non-printable character instead of leaving the char button blank

**Comment by hackmanschorsch** [comment]
In my opinion this strongly depends on the installed fonts of the operating system of the user. So the user has to
1. find a font for his special case
2. install it on his operating system
3. then it is selectable in the text editor in Transkribus
Otherwise Transkribus has to contain all possible fonts in the installation package which increases its size dramatically. We (or the users) could provide a list of useful fonts in the Wiki.
