### ISSUE TITLE
Image rendering/painting very slow on Windows machines

### ISSUE THREAD

**Issue by jkloe** [Transkribus/TranskribusSwtGui#189]
Seems to be an issue with the advanced graphics system GDI+ on Windows systems which is *not* hardware accelerated. Rendering time is not a problem on other systems (Linux and Mac).

Possible solution: render image into different graphcis context and apply transformations directly.

**Comment by jkloe** [comment]
Problem should be fixed with commit 6234f2f66c0823d81463d1af6bdd0efe8564a6d6

Exception: rotation is still performed with the usual transformations, which slows down operations if a rotation is set.

**Comment by kahlep** [comment]
The Canvas background is white for me since this commit and setting it (https://github.com/Transkribus/TranskribusSwtGui/blob/754d1decbd87f217579177f53194c14448a41020/src/main/java/eu/transkribus/swt_gui/canvas/SWTCanvas.java#L144), e.g. via config.properties canvasBackgroundColor, has no effect anymore.

**Comment by kahlep** [comment]
There is an issue with image scaling when using the new paint() method. Undo changes from 
2b87b60 and open trpProd docId = 42727, page 1 to reproduce

**Comment by kahlep** [comment]
Works for me with latest commit! Thanks
