### ISSUE TITLE
Implement "Add Page" in Document Manager

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#49]
The functionality to add a page (including a new image file) is already implemented on the server side.
Should be also available via the document manager in the GUI.

**Comment by fd17** [comment]
Implemented functionality to add page in document manager and toolbar.
Since thumbnails of newly uploaded pages are not immediately available on the server, the document manager uses a scaled version of the full page image as thumbnail whenever a new page is added. Might need to find a faster method when lots of pages are added this way in the future.
