### ISSUE TITLE
Document uploader is not allowed to delete his doc

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TranskribusSwtGui#56]
Only the collection owner is allowed to do this at the moment. Would be more logical if the uploader is also allowed to delete his own document !?

**Comment by kahlep** [comment]
fixed with 77cb7893887bf01f258a7f875f91c55f4f39b6aa and 6e3a7280445617604ff10c739d5f6f6f5756e769

Admin and uploader is allowed to delete a document. Also Storage.collId is sent to the server with request now (instead of first ID from docMd.collList) as the role of the user in this collection might be needed on the server
